import React from "react";
import { Link } from "react-router-dom";
import styled from "styled-components";
import { MainHeader } from "../components";

const H1 = styled.h1`
  font-weight: 700;
  font-size: 200%;
`;
const Strong = styled.strong`
  font-weight: 700;
`;
const H2 = styled.h2`
  font-family: "Etoile";
  font-size: 175%;
`;
const H3 = styled.h3`
  font-family: "Etoile";
  font-size: 150%;
`;
const PrivacyPolicy = () => {
  return (
    <article>
      <MainHeader />
      <div class="page-body">
        <H1>
          <Strong>Privacy Policy</Strong>
        </H1>
        <p>Last updated: February 09, 2021</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when <em>you</em>{" "}
          use the site and tells you about your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
        <H1>
          <Strong>Interpretation and Definitions</Strong>
        </H1>
        <H2>
          <Strong>Interpretation</Strong>
        </H2>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <H2>
          <Strong>Definitions</Strong>
        </H2>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li>
            <Strong>Account</Strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Company</Strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Laudebugs.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Cookies</Strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>

          <li>
            <Strong>Country</Strong> refers to: New York, United States
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Device</Strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Personal Data</Strong> is any information that relates to an
            identified or identifiable individual.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Service</Strong> refers to the Website.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Service Provider</Strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Third-party Social Media Service</Strong> refers to any
            website or any social network website through which a User can log
            in or create an account to use the Service.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Usage Data</Strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Website</Strong> refers to Laurence, accessible from 
            <Link href="/">https://laudebugs.me/#/</Link>
          </li>
        </ul>
        <ul>
          <li>
            <Strong>You</Strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
        <H1>
          <Strong>Collecting and Using Your Personal Data</Strong>
        </H1>
        <H2>
          <Strong>Types of Data Collected</Strong>
        </H2>
        <H3>
          <Strong>Personal Data</Strong>
        </H3>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul>
          <li>Email address - when you submit comments</li>
        </ul>
        <ul>
          <li>First name and last name - when you submit comments</li>
        </ul>
        <ul>
          <li>
            Address, State, Province, ZIP/Postal code, City - when you use the
            Website
          </li>
        </ul>
        <ul>
          <li>Usage Data</li>
        </ul>
        <H3>
          <Strong>Usage Data</Strong>
        </H3>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as Your Device&#x27;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </p>
        <p>
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </p>
        <H3>
          <Strong>Tracking Technologies and Cookies</Strong>
        </H3>
        <p>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </p>
        <ul>
          <li>
            <Strong>Cookies or Browser Cookies.</Strong> A cookie is a small
            file placed on Your Device. You can instruct Your browser to refuse
            all Cookies or to indicate when a Cookie is being sent. However, if
            You do not accept Cookies, You may not be able to use some parts of
            our Service. Unless you have adjusted Your browser setting so that
            it will refuse Cookies, our Service may use Cookies.
          </li>
        </ul>
        <p>
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
          Persistent Cookies remain on Your personal computer or mobile device
          when You go offline, while Session Cookies are deleted as soon as You
          close Your web browser. Learn more about cookies: 
          <Link href="https://www.privacypolicies.com/blog/cookies/">
            What Are Cookies?
          </Link>
          .
        </p>
        <p>
          We use both Session and Persistent Cookies for the purposes set out
          below:
        </p>
        <ul>
          <li>
            <Strong>Necessary / Essential Cookies</Strong>
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>
            <p>
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these Cookies, the services that You
              have asked for cannot be provided, and We only use these Cookies
              to provide You with those services.
            </p>
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Cookies Policy / Notice Acceptance Cookies</Strong>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </p>
          </li>
        </ul>
        <ul>
          <li>
            <Strong>Functionality Cookies</Strong>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use the Website.
            </p>
          </li>
        </ul>
        <p>
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the Cookies
          section of our Privacy Policy.
        </p>
        <H2>
          <Strong>Use of Your Personal Data</Strong>
        </H2>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li>
            <Strong>To provide and maintain our Service</Strong>, including to
            monitor the usage of our Service.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>To manage Comments posted by you on the site:</Strong> To
            post a comment to the site means you have to provide an email and or
            name in order to ensure that you are human. The identifying
            information you provide will not be used for anything else and will
            not be revealed on the site
          </li>
        </ul>
        <ul>
          <li>
            <Strong>For the performance of a contract:</Strong> the development,
            compliance and undertaking of the purchase contract for the
            products, items or services You have purchased or of any other
            contract with Us through the Service.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>To contact You:</Strong> To contact You by email.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>To provide You</Strong> with news, special offers and
            general information about other goods, services and events which we
            offer that are similar to those that you have already purchased or
            enquired about unless You have opted not to receive such
            information.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>To manage Your requests:</Strong> To attend and manage Your
            requests to Us.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>For business transfers:</Strong> We may use Your information
            to evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of Our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by Us about our Service users is among the assets
            transferred.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>For other purposes</Strong>: We may use Your information for
            other purposes, such as data analysis, identifying usage trends,
            determining the effectiveness of our promotional campaigns and to
            evaluate and improve our Service, products, services, marketing and
            your experience.
          </li>
        </ul>
        <p>
          We may share Your personal information in the following situations:
        </p>
        <ul>
          <li>
            <Strong>With Service Providers:</Strong> We may share Your personal
            information with Service Providers to monitor and analyze the use of
            our Service, to contact You.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>For business transfers:</Strong> We may share or transfer
            Your personal information in connection with, or during negotiations
            of, any merger, sale of Company assets, financing, or acquisition of
            all or a portion of Our business to another company.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>With Affiliates:</Strong> We may share Your information with
            Our affiliates, in which case we will require those affiliates to
            honor this Privacy Policy. Affiliates include Our parent company and
            any other subsidiaries, joint venture partners or other companies
            that We control or that are under common control with Us.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>With business partners:</Strong> We may share Your
            information with Our business partners to offer You certain
            products, services or promotions.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>With other users:</Strong> when You share personal
            information or otherwise interact in the public areas with other
            users, such information may be viewed by all users and may be
            publicly distributed outside. If You interact with other users or
            register through a Third-Party Social Media Service, Your contacts
            on the Third-Party Social Media Service may see Your name, profile,
            pictures and description of Your activity. Similarly, other users
            will be able to view descriptions of Your activity, communicate with
            You and view Your profile.
          </li>
        </ul>
        <ul>
          <li>
            <Strong>With Your consent</Strong>: We may disclose Your personal
            information for any other purpose with Your consent.
          </li>
        </ul>
        <H2>
          <Strong>Retention of Your Personal Data</Strong>
        </H2>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </p>
        <H2>
          <Strong>Transfer of Your Personal Data</Strong>
        </H2>
        <p>
          Your information, including Personal Data, is processed at the
          Company&#x27;s operating offices and in any other places where the
          parties involved in the processing are located. It means that this
          information may be transferred to — and maintained on — computers
          located outside of Your state, province, country or other governmental
          jurisdiction where the data protection laws may differ than those from
          Your jurisdiction.
        </p>
        <p>
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </p>
        <p>
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </p>
        <H2>
          <Strong>Data Deletion Requests</Strong>
        </H2>
        <p>
          If you would like any data you provided to the site to be deleted, you
          can do so by submiting a request
          <Link href="https://laudebugs.me/#/data-deletion">here</Link> and can
          be done in two ways:
        </p>
        <H3>1. Personal Identifying Information Data Deletion</H3>
        <p>
          Such a request will be granted to deletion of information that can
          identify you - including email and name that you provide to the
          website
        </p>
        <H3>2. All Data Deletion Request</H3>
        <p>
          This will delete any data that you submit to the site - including your
          name, email and comments that you provide to the Website
        </p>
        <H2>
          <Strong>Disclosure of Your Personal Data</Strong>
        </H2>
        <H3>
          <Strong>Business Transactions</Strong>
        </H3>
        <p>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <H3>
          <Strong>Law enforcement</Strong>
        </H3>
        <p>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </p>
        <H3>
          <Strong>Other legal requirements</Strong>
        </H3>
        <p>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <ul>
          <li>Comply with a legal obligation</li>
        </ul>
        <ul>
          <li>Protect and defend the rights or property of the Company</li>
        </ul>
        <ul>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
        </ul>
        <ul>
          <li>
            Protect the personal safety of Users of the Service or the public
          </li>
        </ul>
        <ul>
          <li>Protect against legal liability</li>
        </ul>
        <H2>
          <Strong>Security of Your Personal Data</Strong>
        </H2>
        <p>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
        <H1>
          <Strong>Children&#x27;s Privacy</Strong>
        </H1>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </p>
        <p>
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent&#x27;s consent before We collect and use that
          information.
        </p>
        <H1>
          <Strong>Children&#x27;s Privacy</Strong>
        </H1>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </p>
        <p>
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent&#x27;s consent before We collect and use that
          information.
        </p>
        <H1>
          <Strong>Links to Other Websites</Strong>
        </H1>
        <p>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&#x27;s site. We Strongly advise You to review the
          Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <H1>
          <Strong>Changes to this Privacy Policy</Strong>
        </H1>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <H1>
          <Strong>Contact Us</Strong>
        </H1>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul>
          <li>By email: lbugasu@gmail.com</li>
        </ul>
        <ul>
          <li>
            By visiting this page on our website: 
            <Link to="/contact">https://laudebugs.me/#/contact</Link>
          </li>
        </ul>
        <p>Privacy Policy for Laurence</p>
      </div>
    </article>
  );
};
export default PrivacyPolicy;
